name: Update and Build Docker Image

on:
  repository_dispatch:
    types: [new_release]

jobs:
  update-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Update repository
        run: echo ${{ github.event.client_payload.release_version }} >> coincoin.txt
